# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MatchGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MatchGame

  target 'MatchGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MatchGameUITests' do
    # Pods for testing
  end

end
